InterfaceTestPlatform/Api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include

from . import views

app_name = 'Api'  # 声明app
urlpatterns = [
    path('get_pj_data/', views.get_pj_data, name='get_pj_data'),
    path('get_inter_data/', views.get_inter_data, name='get_inter_data'),
    path('project_data/', views.project_data, name='project_data'),
    path('perform_data/', views.perform_data, name='perform_data'),
]

InterfaceTestPlatform/TestPlatform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TestPlatform_User.urls')),
    path('api/', include('Api.urls')),
]

InterfaceTestPlatform/TestPlatform_User/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'TestPlatform_User'  # 声明app
urlpatterns = [
    path('home/', views.Home, name='Home'),
    path('', views.Login, name='Login'),
    path('logout/', views.Logout, name='Logout'),
    path('register/', views.Register, name='Register'),
    path('project_list/', views.Project_List, name='Project_List'),
    path('project_info/', views.Project_Info, name='Project_Info'),
    path('interface_list/', views.Interface_List, name='Interface_List'),
    path('interface_perform/', views.Interface_Perform, name='Interface_Perform'),
    path('add_project/', views.Add_Project, name='Add_Project'),
    path('add_pj/', views.Add_Pj, name='Add_Pj'),
    path('sendemail/', views.SendMail, name='SendMail'),
    path('SendEmail/', views.SendEmail, name='SendEmail'),
    path('upload_excel/', views.UploadExcel, name='UploadExcel'),
    path('edit_project/', views.Edit_Project, name='Edit_Project'),
    path('detail_project/', views.Detail_Project, name='Detail_Project'),
    path('delete_data/', views.Delete_Data, name='Delete_Data'),
    path('delete_pj/', views.Delete_Pj, name='Delete_Pj'),
    path('update_data_if/', views.Update_Data_If, name='Update_Data_If'),
    path('batch_delete_if/', views.Batch_Delete_If, name='Batch_Delete_If'),
    path('batch_delete_pj/', views.Batch_Delete_Pj, name='Batch_Delete_Pj'),
    path('update_data_pj/', views.Update_Data_Pj, name='Update_Data_Pj'),
    path('pj_uploadexcel/', views.Pj_UploadExcel, name='Pj_UploadExcel'),
    path('batch_perform_if/', views.Batch_Perform_If, name='Batch_Perform_If'),
    path('perform_result/', views.Perform_Result, name='Perform_Result'),
    path('report/', views.Report, name='Report'),

]

InterfaceTestPlatform/TestPlatform_User/models.py
from django.db import models


# Create your models here.

# 创建表 需要注册表：python3 manage.py makemigrations   同步：migrate
class Project_Data(models.Model):
    id = models.AutoField(primary_key=True)
    pj_id = models.IntegerField()
    pj_name = models.CharField(max_length=10)
    pj_pname = models.CharField(max_length=10)
    pj_pn = models.CharField(max_length=10)
    pj_tname = models.CharField(max_length=10)
    pj_state = models.CharField(max_length=6)


class Interface_Data(models.Model):
    id = models.AutoField(primary_key=True)
    in_id = models.IntegerField()
    in_mname = models.CharField(max_length=10)
    in_type = models.CharField(max_length=8)
    in_url = models.CharField(max_length=100)
    in_data_type = models.CharField(max_length=8)
    in_data = models.CharField(max_length=50)
    in_tname = models.CharField(max_length=10)
    in_expected_result = models.IntegerField()
    in_actual_result = models.CharField(max_length=20)
    status = models.IntegerField()

# def __unicode__(self):
#     return self.pj_id

InterfaceTestPlatform/TestPlatform_User/forms.py
# -*- coding: utf-8 -*-
from django import forms


# class add_pj(forms.Form):
#     pj_name = forms.CharField(label='项目名称')
#     pj_person = forms.CharField(label='项目经理')
#
#

InterfaceTestPlatform/TestPlatform_User/views.py
import ast
from string import Template
from venv import logger
import yagmail
from django.db import transaction
from django.db.models import F
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login, logout  # 从app导入
from django.contrib.auth.forms import UserCreationForm  # 自带创建用户表单，注册
import xlrd, xlwt, json, sys
import requests
from . import models
from .models import Project_Data, Interface_Data
import datetime, time
import unittest
import os
from . import HTMLTestRunnerCN
from jinja2 import Environment, FileSystemLoader
from pyecharts.globals import CurrentConfig

CurrentConfig.GLOBAL_ENV = Environment(loader=FileSystemLoader(
    "/Users/caozheng/Library/Preferences/PyCharm2018.3/TestPlatform_Cz/InterfaceTestPlatform/templates"))
from pyecharts import options as opts
from pyecharts.charts import Bar
from django.http import JsonResponse


# from .test_case import suite


# Create your views here.
def Home(request):  # 首页
    pj_name = models.Project_Data.objects.all().values()
    interface_num = models.Interface_Data.objects.all().values()
    pjNameList = []
    pj_id_num = []
    pj_interface_num = []
    result = []
    for i in pj_name:
        for key1, value1 in i.items():
            if key1 == 'pj_name':
                pjNameList.append(value1)
            if key1 == 'id':
                pj_id_num.append(value1)
    for j in pj_id_num:  # 判断项目id和接口status对应的有多少条用例
        pj_interface_num.append(models.Interface_Data.objects.filter(status=j).count())
        result.append(models.Interface_Data.objects.filter(status=j, in_expected_result=F('in_actual_result')).count())
    return render(request, 'Page/Home.html',
                  {'pjNameList': pjNameList, 'pj_interface_num': pj_interface_num, 'result': result})


def Login(request):  # 登录功能
    if request.method == "POST":
        user = authenticate(request, username=request.POST['username'],
                            password=request.POST['password'])
        if user is None:
            # username = {'name': request.user.username}
            return render(request, 'Page/Login.html', {'error': '用户名或密码不正确'})
        else:
            login(request, user)  # 登录函数
            request.user.get_username()  # request传递登录的用户名
            return redirect('TestPlatform_User:Home')  # 重定向到Home 详情见url中
    else:
        return render(request, 'Page/Login.html')


def Logout(request):  # 登出功能
    logout(request)
    return redirect('TestPlatform_User:Login')  # 重定向


def Register(request):  # 注册功能
    if request.method == "POST":
        register_form = UserCreationForm(request.POST)
        if register_form.is_valid():  # 返回真假，表单是否填写正确
            register_form.save()  # 保存到后台
            user = authenticate(username=register_form.cleaned_data['username'],
                                password=register_form.cleaned_data['password1'])
            login(request, user)
            return redirect('TestPlatform_User:Home')
    else:
        register_form = UserCreationForm()
    content = {"register_form": register_form}
    return render(request, 'Page/Register.html', content)


def Project_List(request):  # 项目列表跳转
    return render(request, 'Page/Project_List.html')


def Project_Info(request):  # 项目信息跳转
    pj_name = request.POST.get('pj_name')
    if pj_name != None:
        global pjName
        pjName = pj_name
        return render(request, 'Page/Project_Info.html', {'pj_name': pjName})
    return render(request, 'Page/Project_Info.html', {'pj_name': pjName})


def Interface_List(request):  # 接口列表跳转
    return render(request, 'Page/Interface_List.html')


def Interface_Perform(request):  # 单条接口执行
    if request.method == "POST":
        in_url = request.POST.get('in_url')
        in_data = request.POST.get('in_data')
        in_expected_result = request.POST.get('in_expected_result')
        in_type = request.POST.get('in_type')
        if in_type == 'POST':
            res = requests.post(url=in_url, data=in_data, json=json.dumps(in_data))
            result = res.json()
            in_data_json = json.dumps(result, indent=4, ensure_ascii=False, sort_keys=True)
            # colorfule_json = highlight(in_data_json,lexers.JsonLexer(),formatters.TerminalFormatter())    # json美化
            in_actual_result = res.status_code  # 获取code对应value值
            if int(in_actual_result) == int(in_expected_result):  # 需要转换为int，虽然看着一样，但类型不同，string类型
                return render(request, 'Page/Interface_Perform.html',
                              {'json_msg': in_data_json, 'headers_msg': res.headers, 'actual_result': in_actual_result,
                               'state': '测试通过！'})
            else:
                return render(request, 'Page/Interface_Perform.html',
                              {'state': '测试不通过,预期结果与实际结果不符！', 'actual_result': in_actual_result})
        elif in_type == 'GET':
            res = requests.get(url=in_url, params=in_data)
            # in_data_json = json.dumps(res, indent=4, ensure_ascii=False, sort_keys=True)
            in_actual_result = res.status_code
            if int(in_actual_result) == int(in_expected_result):
                return render(request, 'Page/Interface_Perform.html',
                              {'json_msg': res, 'headers_msg': res.headers,
                               'actual_result': in_actual_result,
                               'state': '测试通过！'})
            else:
                return render(request, 'Page/Interface_Perform.html',
                              {'json_msg': 'ERROR!预期结果与实际结果不符！' + str(in_actual_result),
                               'state': '测试不通过,预期结果与实际结果不符！',
                               'actual_result': in_actual_result})

        return render(request, 'Page/Interface_Perform.html')
    else:
        return render(request, 'Page/Interface_Perform.html')


def Add_Project(request):  # 点击新增跳转出页面
    return render(request, 'Page/Add_Project.html')


def Add_Pj(request):  # 添加部门信息
    if request.method == 'POST':
        pj_id = request.POST.get('pj_id')
        pj_name = request.POST.get('pj_name')
        pj_pname = request.POST.get('pj_pname')
        pj_pn = request.POST.get('pj_pn')
        pj_tname = request.POST.get('pj_tname')
        pj_state = request.POST.get('pj_state')
        add_project = Project_Data(pj_id=pj_id, pj_name=pj_name, pj_pname=pj_pname, pj_pn=pj_pn, pj_tname=pj_tname,
                                   pj_state=pj_state)
        add_project.save()
        return HttpResponse()


def Delete_Data(request):  # 删除接口信息
    if request.method == "POST":
        data_id = request.POST.get('data_id')  # 获取前端ajax传入的值
        models.Interface_Data.objects.filter(id=data_id).delete()
    return render(request, 'Page/Interface_List.html')


def Delete_Pj(request):  # 删除项目信息及项目下的接口信息
    if request.method == "POST":
        data_id = request.POST.get('data_id')  # 获取前端ajax传入的值
        models.Project_Data.objects.filter(id=data_id).delete()
        data_list = models.Interface_Data.objects.all().values()
        for i in data_list:  # 获得列表中的每个字典
            for key, value in i.items():  # 获取字典中的每个字段及value
                if key == 'status' and str(value) == data_id and value is not None:  # 只把status存入status_arr列表中
                    models.Interface_Data.objects.filter(status=data_id).delete()  # 当删除项目时将项目下的接口信息一同删除
                else:
                    continue
    return render(request, 'Page/Interface_List.html')


def Batch_Delete_If(request):  # 批量删除接口信息
    if request.method == "POST":
        arr = request.POST.get('arr')  # 获得前端JSON.stringify(data);传回的一个列表
        data = json.loads(arr)  # 将获得到的json数据转化成python类型数据（列表中包含多个字典 type(data)为列表）
        id_arr = []  # 创建一个列表存放解析出来的id
        for i in data:  # 获得列表中的每个字典
            for key, value in i.items():  # 获取字典中的每个字段及value
                if key == 'id':  # 只把id存入id_arr列表中
                    id_arr.append(value)
        for j in id_arr:  # 循环列表按照id值进行删除操作
            models.Interface_Data.objects.filter(id=j).delete()
        return render(request, 'Page/Interface_List.html')
    return render(request, 'Page/Interface_List.html')


def Batch_Perform_If(request):  # 批量执行功能
    if request.method == "POST":
        arr = request.POST.get('arr')
        data = json.loads(arr)
        for i in data:  # 获得列表中的每个字典
            if i['in_type'].upper() == 'POST':
                res = requests.post(url=i['in_url'], data=i['in_data'],
                                    json=json.dumps(i['in_data']))  # 接口执行方法 使用requests库处理接口
                models.Interface_Data.objects.filter(id=i['id']).update(
                    in_actual_result=res.status_code)  # res.status_code获取code对应value值
                continue
            elif i['in_type'].upper() == 'GET':
                res = requests.get(url=i['in_url'], params=i['in_data'])
                models.Interface_Data.objects.filter(id=i['id']).update(in_actual_result=res.status_code)
                continue
        return render(request, 'Page/Perform_Result.html')


def Perform_Result(request):
    return render(request, 'Page/Perform_Result.html')


def Batch_Delete_Pj(request):  # 批量删除接口信息
    if request.method == "POST":
        arr = request.POST.get('arr')  # 获得前端JSON.stringify(data);传回的一个列表
        data = json.loads(arr)  # 将获得到的json数据转化成python类型数据（列表中包含多个字典 type(data)为列表）
        id_arr = []  # 创建一个列表存放解析出来的id
        for i in data:  # 获得列表中的每个字典
            for key, value in i.items():  # 获取字典中的每个字段及value
                if key == 'id':  # 只把id存入id_arr列表中
                    id_arr.append(value)
        for j in id_arr:  # 循环列表按照id值进行删除操作
            models.Project_Data.objects.filter(id=j).delete()
        return render(request, 'Page/Interface_List.html')
    return render(request, 'Page/Interface_List.html')


def Update_Data_If(request):  # 修改接口信息
    if request.method == "POST":
        id = request.POST.get('data_id')

InterfaceTestPlatform/TestPlatform_User/templates/Page/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>登录</title>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static '/css/layui.css' %}">
    <style type="text/css">

    </style>
</head>
<body>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:10%;padding-left:45%;">
    <legend>Test Platform</legend>
</fieldset>
<div class="center" style="text-align: center; ">
    <h1>　　</h1>
    <h1>　　</h1>


    <form action="" method="post" class="layui-form layui-form-pane">
        {% csrf_token %}
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label" style="margin-left: auto">用户名</label>
                <div class="layui-input-inline">
                    <input type="text" name="username" required lay-verify="required" lay-verType="tips"
                           placeholder="请输入用户名" autocomplete="off" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-inline">
                <label class="layui-form-label">密码</label>
                <div class="layui-input-inline">
                    <input type="password" name="password" required lay-verify="required" lay-verType="tips"
                           placeholder="请输入密码" autocomplete="off" class="layui-input">
                </div>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-show-sm-inline-block">
                <div class="layui-form-mid layui-word-aux">{{error}}</div>
            </div>
        </div>
        <div class="layui-form-item">
            <button class="layui-btn layui-btn-radius" type="submit">登 录</button>
        <!--<a href="{%url 'TestPlatform_User:Register' %}">-->
            <button class="layui-btn layui-btn-radius" type="button" onclick="msg()" style="margin-left: 100px">注 册</button>
        </a>
        </div>
    </form>
</div>
{% load static %}
<script src="{% static '/js/layui.js' %}" charset="utf-8"></script>
<script type="text/javascript">
    function msg() {
        layer.msg('暂未开放该功能！请联系管理员注册账号！', { icon: 4, time: 2000 }, function () {
            // 关闭弹出层
            var index = parent.layer.getFrameIndex(window.name);
            parent.layer.close(index);
        });
    }

</script>
</body>
</html>

InterfaceTestPlatform/TestPlatform_User/templates/Page/Project_Info.html
<!DOCTYPE html>
<html lang="en" style="transition: background-color 0.15s ease 0s;">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>接口列表</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static '/css/layui.css' %}">
    <link rel="stylesheet" href="{% static '/css/modules/layer/default/layer.css' %}">
</head>
<body>
<div class="layui-layout layui-layout-admin">
    <div class="layui-header header header-demo" style="background-color: #393D49">
        <div class="layui-main">
            <ul class="layui-nav">
                <button style="background-color: #393D49;margin-left: -20px;" type="button"
                        class="layui-btn layui-btn-normal"><i
                        class="layui-icon"></i></button>
                <li class="layui-nav-item"><a href="{%url 'TestPlatform_User:Home'%}"><h1>TestPlatform</h1></a></li>
                <li class="layui-nav-item">
                    <a href="{%url 'TestPlatform_User:Project_List'%}">项目列表</a>
                <li class="layui-nav-item">
                    <a href="{%url 'TestPlatform_User:Interface_List'%}">接口列表</a>
                </li>
                <li class="layui-nav-item">
                    <a href="{%url 'TestPlatform_User:Interface_Perform'%}">快速执行</a>
                </li>
                <li class="layui-nav-item"><a href="">测试报告</a></li>
                <li class="layui-nav-item"><a href="">邮件配置</a></li>
                <li class="layui-nav-item" style="float: right">
                    <a href="javascript:;">{{ user.get_username }}</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{%url 'TestPlatform_User:Logout'%}"><i
                                class="layui-icon">&#xe64d; </i>登出</a></dd>
                    </dl>
                </li>
                <li style="margin:12px;float: right">
                    <div style="margin-left: 30px;">
                        <input type="hidden" name="color" value="" id="test-all-input">
                        <div id="test-all"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div style="padding: 30px; background-color: #F2F2F2;">
        <div class="layui-upload demoTable ">
            <button type="button" class="layui-btn" id="upload" name="file" style="margin-bottom: 7px"><i
                    class="layui-icon"></i>上传用例
            </button>
            <button type="button" class="layui-btn layui-btn-danger" id="batchDelete" data-type="getCheckData"
                    style="float: right; margin-right: 20px"><i class="layui-icon">&#xe640;</i>批量删除
            </button>
            <!--<button type="button" class="layui-btn layui-btn-warm" id="addInterface"-->
                    <!--style="float: right;margin-right: 20px">新增用例-->
            <!--</button>-->
            <button type="button" class="layui-btn layui-btn-primary layui-border-green" id="batchPerform"
                    data-type="batchPerform"
                    style="float: right; margin-right: 20px"><i class="layui-icon">&#xe605;</i>批量执行
            </button>
            <div style="text-align: center;margin-top: -40px;margin-left: 237px;"><h1>{{pj_name}}</h1></div>
        </div>
        <div class="demoTable" style="margin-top: -45px; margin-left: 100px">
            <div class="layui-inline ">
                <input type="text" class="layui-input" name="id" placeholder="可根据id进行搜索"
                       title="可根据id进行搜索" id="demoReload" autocomplete="off"
                       style="margin-left: 50px;margin-bottom: 2px">
            </div>
            <button class="layui-btn" data-type="reload" style="margin-left: 50px;">搜索</button>
        </div>

        <table class="layui-hide" id="table_data" lay-filter="table_data"></table>
        <script type="text/html" id="toolbar">
            <a class="layui-btn layui-btn-xs" lay-event="perform"
               href="{%url 'TestPlatform_User:Interface_Perform'%}">执行</a>
            <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="edit">修改</a>
            <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
        </script>
    </div>
</div>


{% load static %}
<script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"></script>
<script src="{% static '/js/layui.js' %}" charset="utf-8"></script>
<script src="{% static '/js/lay/modules/upload.js' %}" charset="utf-8"></script>
<!--<script src="{% static '/js/lay/modules/table.js' %}" charset="utf-8"></script>-->
<!--table.js中搜索i.data("edit")改为dblclick-->
<script>
    layui.use('element', function () {
        var element = layui.element; //导航的hover效果、二级菜单等功能，需要依赖element模块
        //监听导航点击
        element.on('nav(table_data)', function (elem) {
            //console.log(elem)
            layer.msg(elem.text());
        });
    });

    layui.use('table', function () {
        var table = layui.table;
        table.on('edit(table_data)', function (obj) {
            var value = obj.value //得到修改后的值
                , data = obj.data //得到所在行所有键值
                , field = obj.field; //得到字段
            layer.confirm('确定将信息修改为：' + value, {
                btn: ['确定', '取消']
            }, function (index) {
                $.ajax({
                    type: 'post',
                    url: "{%url 'TestPlatform_User:Update_Data_If'%}",
                    data: {'data_id': data.id, 'field': field, 'value': value},
                    traditional: true,
                    async: false,
                    success: function (result) {
                    },
                    error: function (result) {
                    }
                });
                // window.location.reload();
                layer.close(index);
            }, function () {
                window.location.reload();
                layer.close(index);
            })
        });

        table.render({
            elem: '#table_data'	//表单ID
            , url: "{%url 'Api:project_data'%}"	//数据接口
            , page: true			//分页设置
            , limit: 20		//默认每一页显示数量
            , limits: [10, 20, 30, 40, 50]		//可选择每页显示的数量
            , toolbar: true
            , cols: [[			//表格列
                {type: 'checkbox', sort: false}
                , {field: 'in_id', title: 'ID', align: 'center',  sort: true, edit: 'int'}
                , {field: 'in_mname', title: '接口名称', sort: false, edit: 'text'}
                , {field: 'in_type', title: '接口类型', align: 'center',sort: false, edit: 'text'}
                , {field: 'in_url', title: '接口地址', sort: false, edit: 'text'}
                , {field: 'in_data', title: '接口参数',  sort: false, edit: 'text'}
                , {field: 'in_data_type', title: '数据类型', align: 'center',  sort: false, edit: 'text'}
                , {field: 'in_tname', title: '测试人员', align: 'center',  sort: false, edit: 'text'}
                , {field: 'in_expected_result', title: '预期结果', sort: false, edit: 'text'}
                , {field: 'dobar', title: '操作', align: 'center',width:200, sort: false, toolbar: '#toolbar'}
            ]]
            , response: {
                statusCode: 200
            }
            , id: 'testReload'
            , parseData: function (res) { //将原始数据解析成 table 组件所规定的数据，res为从url中get到的数据
                var result;
                // console.log(this);
                // console.log(JSON.stringify(res));
                if (this.page.curr) {
                    result = res.data.slice(this.limit * (this.page.curr - 1), this.limit * this.page.curr);
                } else {
                    result = res.data.slice(0, this.limit);
                }
                return {
                    "code": res.code, //解析接口状态
                    "msg": res.msg, //解析提示文本
                    "count": res.count, //解析数据长度
                    "data": result //解析数据列表
                };
            }
        });
        var $ = layui.$, active = {
            reload: function () {
                var demoReload = $('#demoReload');
                if (demoReload.val() === "") {
                    location.reload();
                } else {
                    //执行重载
                    table.reload('testReload', {
                        page: {
                            curr: 1 //重新从第 1 页开始
                        }
                        , where: {
                            id: demoReload.val(),
                        }
                    });
                }
            },
            getCheckData: function () { //获取选中数据
                var checkStatus = table.checkStatus('testReload')
                    , data = checkStatus.data;
                var arr = JSON.stringify(data);
                if (data.length === 0) {
                    layer.msg('请选择需要删除的数据！')
                } else {
                    layer.confirm('是否删除选中的' + data.length + '条数据？', function (index) {
                        $.ajax({
                            type: 'post',
                            url: "{%url 'TestPlatform_User:Batch_Delete_If'%}",
                            data: {'arr': arr},
                            traditional: true,
                            async: false,
                        });
                        window.location.reload();
                    });
                }
            }
            , batchPerform: function () {
                var checkStatus = table.checkStatus('testReload')
                    , data = checkStatus.data;
                var arr = JSON.stringify(data);
                if (data.length === 0) {
                    layer.msg('请选择需要执行的数据！')
                } else {
                    $.ajax({
                        type: 'POST',
                        url: "{%url 'TestPlatform_User:Batch_Perform_If'%}",
                        data: {'arr': arr},
                        traditional: true,
                        async: false,
                    });
                    $.ajax({
                        type: 'POST',
                        url: "{%url 'Api:perform_data'%}",
                        data: {'arr': arr},
                        traditional: true,
                        async: false,
                    });
                    window.location = "http://localhost:8000/perform_result/";
                    // window.location.reload();
                }
            }
        };

        $('.demoTable .layui-btn').on('click', function () {
            var type = $(this).data('type');
            active[type] ? active[type].call(this) : '';
        });
    });


    //上传功能
    layui.use('upload', function () {
        var $ = layui.jquery
            , upload = layui.upload;
        var storage = window.sessionStorage;
        id = storage.id;
        upload.render({
            elem: '#upload'
            , url: "{% url 'TestPlatform_User:Pj_UploadExcel' %}" //改成自己的上传路径
            , accept: 'file'
            , auto: true
            , data: {     //layui upload传参方式
                id: id
            }
            , done: function (res) {
                console.log(res);
                if ('{{message}}' === '导入失败') {
                    layer.msg('上传失败');
                } else {
                    // layer.load(1, {time: 10 * 100});
                    layer.msg('上传成功');
                    setTimeout("window.location.reload()", 700);
                }
            }
        });
    });
    layui.use('table', function () {
        var table = layui.table;
        //监听表格复选框选择
        table.on('checkbox(table_data)', function (obj) {
            console.log(obj)
        });
        //监听工具条 删除一条数据
        table.on('tool(table_data)', function (obj) {
            var data = obj.data;
            if (obj.event === 'del') {
                layer.confirm('真的删除行么', function (index) {
                    $.ajax({
                        type: 'post',
                        url: "{%url 'TestPlatform_User:Delete_Data'%}",
                        data: {'data_id': data.id},
                        traditional: true,
                        async: false,
                        success: function (result) {
                        },
                        error: function (result) {
                        }
                    });
                    obj.del();
                    layer.close(index);
                });
            } else if (obj.event === 'edit') {
                layer.msg('双击单元格试试!');
            } else if (obj.event === 'perform') {  //选中一条数据点击执行，使用sessionStorage存储数据
                var storage = window.sessionStorage;
                storage['in_url'] = data.in_url;
                storage['in_data'] = data.in_data;
                storage['in_type'] = data.in_type;
                storage['in_data_type'] = data.in_data_type;
                storage['in_expected_result'] = data.in_expected_result;
            }
        });
    });

</script>
</body>
</html>